on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, new test!

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        run: ./gradlew assemble

      - name: Build with gradle
        run: chmod +x ./gradlew build

      - name: Upload apk
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app
          path: app/build/outputs/apk/
