on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        run: ./gradlew assemble

      - name: Build with gradle
        if: github.event.schedule != '30 2 * * 2'
        run: chmod +x ./gradlew build

      - name: Upload apk
        if: github.event.schedule != '30 2 * * 2'
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app
          path: app/build/outputs/apk/local/debug/*.apk
      #          path: app/build/outputs/apk/local/release   --generate release flavor
      #          path: app/build/outputs/apk/local/   --generate all flavor

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Unit test
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testLocalDebugUnitTest


  instrumentation-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run espresso test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/


