on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        run: ./gradlew assemble

      - name: Build with gradle
        run: chmod +x ./gradlew build

      - name: Upload apk
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app
          path: app/build/outputs/apk/local/debug
      #          path: app/build/outputs/apk/local/release   --generate release flavor
      #          path: app/build/outputs/apk/local/   --generate all flavor

      - name: Unit test
        run: ./gradlew test
  instrumentation-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run esresso test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

